FROM node

RUN npm install nodemon -g

WORKDIR /src
COPY . /src
RUN npm install

EXPOSE 8080
EXPOSE 5858
ENTRYPOINT ["/bin/bash", "-c", "if [ -z \"$REMOTE_DEBUGGING\" ]; then nodemon -L --debug; else nodemon -L --debug-brk; fi"]